version: '2'

services:

  keycloak-server-ssl:
    container_name: 'keycloak-server-ssl'
    image: leanda
    build:
      context: .
    environment:
      - DB_VENDOR=H2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - kkdata:/data

volumes:
  kkdata:
