version: '2'

services:

  keycloak-server-ssl-test:
    container_name: 'keycloak-server-ssl-test'
    image: jboss/keycloak:4.8.3.Final
    environment:
      - DB_VENDOR=H2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - kkdata:/data
      - ./certs:/etc/x509/https

volumes:
  kkdata:
